CREATE TABLE Athlete (
	ID INTEGER PRIMARY KEY,
	Name VARCHAR(100) NOT NULL,
	Sex CHAR(1) CHECK(Sex='F' OR Sex='M') NOT NULL,
	Height INTEGER CHECK(Height>0)
);
CREATE TABLE Team (
	Team VARCHAR(100) PRIMARY KEY,
	NOC VARCHAR(100) NOT NULL
);
CREATE TABLE Games (
	Games VARCHAR(100) PRIMARY KEY,
	Year INTEGER NOT NULL,
	Season VARCHAR(100) NOT NULL,
	City VARCHAR(100) NOT NULL
);
CREATE TABLE Event (
	Event VARCHAR(100) PRIMARY KEY,
	Sport VARCHAR(100) NOT NULL,
	Games VARCHAR(100),
	FOREIGN KEY (Games) REFERENCES Games(Games)
);
CREATE TABLE Participated (
	ID INTEGER,
	Team VARCHAR(100),
	Event VARCHAR(100),
	Games VARCHAR(100),
	Age Integer,
	Weight real,
	Medal VARCHAR(100) CHECK(Medal='Gold' OR Medal='Silver' OR Medal='Bronze'),
	FOREIGN KEY (ID) REFERENCES Athlete(ID),
	FOREIGN KEY (Team) REFERENCES Team(Team),
	FOREIGN KEY (Event) REFERENCES Event(Event),
	FOREIGN KEY (Games) REFERENCES Games(Games)
);
